spring.application.name=SpringUnitProject
spring.datasource.url=jdbc:postgresql://localhost:9876/unitprojectdb
spring.datasource.username=postgres
spring.datasource.password=Kaden12162006

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true